mongodbUri  = "mongodb+srv://root:VTT711ZUg7ldZY9C@sellaro-dev.kwlac5h.mongodb.net/?retryWrites=true&w=majority&appName=sellaro-dev"
wppApiToken = "B6D711FCDE4D4FD5936544120E713976"
wppUrl      = "https://dev-wpp.sellaro.io"
environment = "dev"
backendUrl  = "https://dev-api.sellaro.io"
